// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWoY6b2-Us0buAsq44CXbTFR5aUGXi_d0',
    appId: '1:173746526719:web:32e69229c0d5ff826fefca',
    messagingSenderId: '173746526719',
    projectId: 'cs310-a6438',
    authDomain: 'cs310-a6438.firebaseapp.com',
    storageBucket: 'cs310-a6438.firebasestorage.app',
    measurementId: 'G-DCHC3NF6Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbfp6dCBNBpUfEG8qVfRu4wvohrbpBi9Q',
    appId: '1:173746526719:android:42fe868feed614196fefca',
    messagingSenderId: '173746526719',
    projectId: 'cs310-a6438',
    storageBucket: 'cs310-a6438.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPbKymUtoTBtX3xVGgcInrH-Ua6ZN6a_8',
    appId: '1:173746526719:ios:7819e74080e8150c6fefca',
    messagingSenderId: '173746526719',
    projectId: 'cs310-a6438',
    storageBucket: 'cs310-a6438.firebasestorage.app',
    iosBundleId: 'com.example.tickTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPbKymUtoTBtX3xVGgcInrH-Ua6ZN6a_8',
    appId: '1:173746526719:ios:7819e74080e8150c6fefca',
    messagingSenderId: '173746526719',
    projectId: 'cs310-a6438',
    storageBucket: 'cs310-a6438.firebasestorage.app',
    iosBundleId: 'com.example.tickTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWoY6b2-Us0buAsq44CXbTFR5aUGXi_d0',
    appId: '1:173746526719:web:68acc7595c6d7a506fefca',
    messagingSenderId: '173746526719',
    projectId: 'cs310-a6438',
    authDomain: 'cs310-a6438.firebaseapp.com',
    storageBucket: 'cs310-a6438.firebasestorage.app',
    measurementId: 'G-NDG5E7L7FL',
  );
}
